- hosts: all
  become: true
  
  tasks:
    - name: Download Docker installation script
      ansible.builtin.get_url:
        url: https://get.docker.com
        dest: ./get-docker.sh
        mode: '0755'

    - name: Run the Docker installation script
      ansible.builtin.shell: ./get-docker.sh

    - name: Ensure Docker service is running
      ansible.builtin.systemd_service:
        name: docker
        state: started
        enabled: true #Enables the service, making sure is present after next system reboot

    - name: Add user to Docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}" #Ansible variable with the current ansible user
        groups: docker
        append: true #Appends the user to the declared group

    - name: Add jenkins user to Docker group
      ansible.builtin.user:
        name: jenkins
        groups: docker
        append: true #Appends the user to the declared group

    - name: Restart docker service
      ansible.builtin.systemd_service:
        name: docker
        state: restarted #To make sure the changes are applied, the service is restarted